### ISSUE TITLE
Show Terms of Use only for Users, which login via Direct Login, don't show Terms of Use for SAML-Logins

### ISSUE THREAD

**Issue by rtt-mmk** [nextcloud/terms_of_service#325] opened 2020-03-26 13:14 UTC
The Terms of service should not be show to users, which login via SAML-Login-Meachanism. 
Only users, which login via "Direct Login" should see the Terms of service on first login,
because SAML-Users already see the Terms during their SAML/SSO-Login-process on a 
other server/page.

It should be possible not to show the Terms of service to SAML-Login-Users, but only to
direct-login users.

**Comment by nickvergessen** [comment] 2020-03-26 14:51
Duplicate of #318 #319

**Closed by nickvergessen** 2020-03-26 14:51 UTC
